### ISSUE TITLE
Problems compiling example

### ISSUE THREAD

**Issue by lonnietc** [pkujhd/godynamic#3]
Hello,

I am running on Ubuntu 20.04 (64-bit) and have just tried to compile up your examples using both Go v1.16 and v1.17 but get the same errors:

I get through these with no problems:

```
export GO111MODULE=auto
go install -buildmode=shared std
go build -linkshared -v github.com/pkujhd/godynamic/examples/loader

```

But then on the next step:

```
go install -v -buildmode=shared -linkshared github.com/pkujhd/godynamic/examples/ubase
```

Output:
```
/test$ go install -v -buildmode=shared -linkshared github.com/pkujhd/godynamic/examples/ubase
# /tmp/go-build180572587/b038/libgithub.com-pkujhd-godynamic-examples-ubase.so
panic: runtime error: makeslice: cap out of range

goroutine 1 [running]:
cmd/link/internal/loader.(*Loader).LoadSyms(0xc00058c000, 0x66f793)
        /home/lonnie/.gvm/gos/go1.17/src/cmd/link/internal/loader/loader.go:2210 +0x9f
cmd/link/internal/ld.(*Link).loadlib(0xc000140000)
        /home/lonnie/.gvm/gos/go1.17/src/cmd/link/internal/ld/lib.go:577 +0x46e
cmd/link/internal/ld.Main(_, {0x20, 0x20, 0x1, 0x7, 0x10, 0x0, {0x0, 0x0}, {0x678977, ...}, ...})
        /home/lonnie/.gvm/gos/go1.17/src/cmd/link/internal/ld/main.go:249 +0xd8b
main.main()
        /home/lonnie/.gvm/gos/go1.17/src/cmd/link/main.go:69 +0x1005
```

Not really sure what is happening here.

Can you please help?

**Comment by pkujhd** [comment]
@lonnietc  please tell me your golang version, like go.1.17.x

it seems a golang compiler bug, so I could not do more things

**Comment by lonnietc** [comment]
@pkujhd I can use just about an Go version, and tried multiple versions with the same result.

Just tried:

```
go version go1.16.0 linux/amd64
```

What version do you use on your side (latest version) and I will try it here.

On a side note, all of my Go versions work perfectly to compile and run other projects with no problems.

In researching this error message, 

```
[panic: runtime error: makeslice: cap out of range](https://stackoverflow.com/questions/50789279/panic-runtime-error-makeslice-cap-out-of-range)
```

I did come across this:

```
https://stackoverflow.com/questions/50789279/panic-runtime-error-makeslice-cap-out-of-range
```

I am looking now to see if something is happening in the "loader" code since that one compiles with no problem but the others are a problem for some reason.

**Comment by lonnietc** [comment]
As an update, I just tried it again with 

Go v1.16.15 

and got the same results so I am still researching the error message to see if I can pinpoint down where the panic is happening in the code.
